name: CloverInvisRegions
version: '${project.version}'
main: org.cloverservices.invisregions.CloverInvisRegions
depend: [ MassiveCore, ProtocolLib, WorldGuard ]
authors: [ Ministry ]
description: Invisible regions made by Clover Services!
